FROM node:argon
MAINTAINER contact "labarretony@gmail.com"

# Create app directory
WORKDIR /usr/src/app


# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install

# Bundle app source
COPY . ./
RUN ls

EXPOSE 8085

# Run app
CMD ["npm", "start"]
