FROM node:argon
MAINTAINER contact "labarretony@gmail.com"

# Create app directory
WORKDIR /usr/src/app


# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install

# Bundle app source
COPY server.js /usr/src/app/
COPY docs/index.html /usr/src/app/docs/index.html
RUN ls

EXPOSE 8086

# Run app
CMD ["npm", "start"]
